# Docker Compose configuration for Auteur Movie Director services
# For local development - production should use Kubernetes or similar
version: '3.8'

services:
  comfyui:
    image: ${COMFYUI_IMAGE:-comfyui/comfyui:latest}
    container_name: amd-comfyui
    profiles:
      - ai
      - comfyui
      - full
    ports:
      - "${COMFYUI_PORT:-8188}:8188"
    volumes:
      - comfyui-models:/models
      - comfyui-input:/input
      - comfyui-output:/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - amd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/system_stats"]
      interval: 30s
      timeout: 10s
      retries: 3

  wan2gp:
    image: ${WAN2GP_IMAGE:-wan2gp/wan2gp:latest}
    container_name: amd-wan2gp
    profiles:
      - ai
      - video
      - full
    ports:
      - "${WAN2GP_PORT:-7860}:7860"
    volumes:
      - wan2gp-models:/models
      - wan2gp-output:/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - amd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  rvc:
    image: ${RVC_IMAGE:-rvc/rvc:latest}
    container_name: amd-rvc
    profiles:
      - ai
      - audio
      - full
    ports:
      - "${RVC_PORT:-7865}:7865"
    volumes:
      - rvc-models:/models
      - rvc-output:/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - amd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7865/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  audioldm:
    image: ${AUDIOLDM_IMAGE:-audioldm/audioldm:latest}
    container_name: amd-audioldm
    profiles:
      - ai
      - audio
      - full
    ports:
      - "${AUDIOLDM_PORT:-7863}:7863"
    volumes:
      - audioldm-models:/models
      - audioldm-output:/output
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - amd-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7863/api/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  amd-network:
    name: ${DOCKER_NETWORK:-amd-network}
    driver: bridge

volumes:
  comfyui-models:
  comfyui-input:
  comfyui-output:
  wan2gp-models:
  wan2gp-output:
  rvc-models:
  rvc-output:
  audioldm-models:
  audioldm-output: