workflow_name: "Character Creation - Basic Consistency"
description: "Generate consistent character images using IPAdapter + InstantID + ControlNet"
version: "1.0"

nodes:
  "1":
    class_type: "CheckpointLoaderSimple"
    inputs:
      ckpt_name: "realisticVisionV60B1_v60B1VAE.safetensors"

  "2":
    class_type: "CLIPTextEncode"
    inputs:
      text: "{character_description}"
      clip: ["1", 1]

  "3":
    class_type: "CLIPTextEncode"
    inputs:
      text: "blurry, low quality, distorted, deformed"
      clip: ["1", 1]

  "4":
    class_type: "LoadImage"
    inputs:
      image: "{reference_image_path}"

  "5":
    class_type: "IPAdapterModelLoader"
    inputs:
      ipadapter_file: "ip-adapter_sd15.bin"

  "6":
    class_type: "IPAdapter"
    inputs:
      model: ["1", 0]
      ipadapter: ["5", 0]
      image: ["4", 0]
      weight: 0.8
      noise: 0.0
      weight_type: "original"
      start_at: 0.0
      end_at: 1.0

  "7":
    class_type: "InstantIDModelLoader"
    inputs:
      instantid_file: "ip-adapter.bin"

  "8":
    class_type: "InstantIDFaceAnalysis"
    inputs:
      provider: "CPU"

  "9":
    class_type: "InstantID"
    inputs:
      instantid: ["7", 0]
      insightface: ["8", 0]
      control_net: ["10", 0]
      image: ["4", 0]
      model: ["6", 0]
      positive: ["2", 0]
      negative: ["3", 0]
      start_at: 0.0
      end_at: 0.8
      weight: 0.8

  "10":
    class_type: "ControlNetLoader"
    inputs:
      control_net_name: "control_v11p_sd15_openpose.pth"

  "11":
    class_type: "OpenPosePreprocessor"
    inputs:
      image: ["4", 0]
      detect_hand: "enable"
      detect_body: "enable"
      detect_face: "enable"

  "12":
    class_type: "ControlNetApply"
    inputs:
      conditioning: ["9", 1]
      control_net: ["10", 0]
      image: ["11", 0]
      strength: 0.6

  "13":
    class_type: "KSampler"
    inputs:
      model: ["9", 0]
      positive: ["12", 0]
      negative: ["9", 2]
      latent_image: ["14", 0]
      seed: "{generation_seed}"
      steps: 25
      cfg: 7.0
      sampler_name: "euler_ancestral"
      scheduler: "normal"
      denoise: 1.0

  "14":
    class_type: "EmptyLatentImage"
    inputs:
      width: 512
      height: 768
      batch_size: 1

  "15":
    class_type: "VAEDecode"
    inputs:
      samples: ["13", 0]
      vae: ["1", 2]

  "16":
    class_type: "SaveImage"
    inputs:
      images: ["15", 0]
      filename_prefix: "character_{character_name}_{timestamp}"

parameter_mapping:
  character_description: "Positive prompt describing the character"
  reference_image_path: "Path to character reference image"
  character_name: "Character name for file naming"
  generation_seed: "Random seed for generation"
  timestamp: "Timestamp for unique file naming"

requirements:
  models:
    - "realisticVisionV60B1_v60B1VAE.safetensors"
    - "ip-adapter_sd15.bin"
    - "control_v11p_sd15_openpose.pth"
  vram_estimate: "6GB"
  processing_time: "30-60 seconds"